<?php

return array (
  'version' => '6.3.5',
  'list_screen' => 
  array (
    'title' => '',
    'type' => 'testimonials',
    'id' => '652971f228129',
    'updated' => 1697216492,
    'columns' => 
    array (
      '6529734aa872b0' => 
      array (
        'type' => 'column-featured_image',
        'label' => 'Image',
        'width' => '130',
        'width_unit' => 'px',
        'featured_image_display' => 'image',
        'image_size' => 'cpac-custom',
        'image_size_w' => '110',
        'image_size_h' => '60',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => '6529734aa872b0',
      ),
      'title' => 
      array (
        'type' => 'title',
        'label' => 'Name',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'name' => 'title',
      ),
      '6529746fd6c8b4' => 
      array (
        'type' => 'column-meta',
        'label' => 'Job title',
        'width' => '',
        'width_unit' => '%',
        'field' => '_rbt_testimonials_title',
        'field_type' => '',
        'before' => '',
        'after' => '',
        'edit' => 'on',
        'editable_type' => 'text',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => '6529746fd6c8b4',
      ),
      65297342856040 => 
      array (
        'type' => 'column-content',
        'label' => 'Content',
        'width' => '',
        'width_unit' => '%',
        'string_limit' => 'word_limit',
        'excerpt_length' => '20',
        'before' => '',
        'after' => '',
        'edit' => 'on',
        'editable_type' => 'textarea',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => '65297342856040',
      ),
      '652973619ced90' => 
      array (
        'type' => 'column-taxonomy',
        'label' => 'Category',
        'width' => '',
        'width_unit' => '%',
        'taxonomy' => 'testimonialcategories',
        'term_link_to' => 'filter',
        'number_of_items' => '10',
        'separator' => 'comma',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => '652973619ced90',
      ),
      '6529748150a3d8' => 
      array (
        'type' => 'column-meta',
        'label' => 'URL',
        'width' => '',
        'width_unit' => '%',
        'field' => '_rbt_testimonials_url',
        'field_type' => '',
        'before' => '',
        'after' => '',
        'edit' => 'on',
        'editable_type' => 'text',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => '6529748150a3d8',
      ),
      '6529733dfba5e4' => 
      array (
        'type' => 'column-status',
        'label' => 'Status',
        'width' => '',
        'width_unit' => '%',
        'use_icon' => '',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => '6529733dfba5e4',
      ),
    ),
    'settings' => 
    array (
      'roles' => 
      array (
      ),
      'users' => 
      array (
      ),
      'sorting' => '0',
      'sorting_order' => 'asc',
      'hide_inline_edit' => 'off',
      'hide_bulk_edit' => 'off',
      'hide_bulk_delete' => 'off',
      'hide_smart_filters' => 'off',
      'hide_segments' => 'off',
      'hide_export' => 'off',
      'hide_conditional_formatting' => 'off',
      'hide_new_inline' => 'off',
      'resize_columns' => 'off',
      'column_order' => 'off',
      'hide_filters' => 'off',
      'hide_filter_post_date' => 'off',
      'hide_submenu' => 'off',
      'hide_search' => 'off',
      'hide_bulk_actions' => 'off',
      'hide_row_actions' => 'off',
      'horizontal_scrolling' => 'off',
      'primary_column' => '',
      'filter_segment' => '',
    ),
  ),
);